services:
  docker-hostfile-sync:
    build:
      context: .
    image: ghcr.io/webproject-xyz/docker-hosts-file-sync
    container_name: docker-hostfile-sync
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/hosts
        target: /app/hosts
#      - type: bind
#        source: .
#        target: /app
    command: --reverse-proxy-host-ip=172.16.238.100
